### ISSUE TITLE
C'est pas clair que c'est le Bonjour

### ISSUE THREAD

**Issue by Dagothig** [Dagothig/le-bonmatin-la-laitue-la-tomate#1]
La Première pourrait dire un shit ou sinon le protagoniste pourrait commenter dessus

**Comment by WilliamBouchard** [comment]
Selon moi la toune rend assez clair que c'est le bonjour

**Comment by 316k** [comment]
Je ne suis pas géologue... Mais selon moi, ça semblait clair que c'était le Bonjour

**Comment by Dagothig** [comment]
La Bonjuritude a été clarifiée grâce à du Dialogue de Qualitay :tm:
